import Layout from '@/components/layout/Layout'
import Breadcrumbs from '@/components/modules/Breadcrumbs/Breadcrumbs'
import OrderPage from '@/components/templates/OrderPage/OrderPage'
import { useUser } from '@/hooks/useUser'
import Head from 'next/head'
import { useCallback, useEffect } from 'react'

export default function Order() {
  const getDefaultTextGenerator = useCallback(() => 'Оформление заказа', [])
  const getTextGenerator = useCallback((param: string) => ({}[param]), [])

  // const { checkUser } = useUser()

  // useEffect(() => {
  //   checkUser()
  // })
  return (
    <>
      <Head>
        <title>Магазин | Заказ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>
      <Layout>
        <main>
          <Breadcrumbs
            getDefaultTextGenerator={getDefaultTextGenerator}
            getTextGenerator={getTextGenerator}
          />
          <OrderPage />
          <div className="overlay"></div>
        </main>
      </Layout>
    </>
  )
}
