import Header from '@/components/modules/Header/Header'
import Head from 'next/head'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="overlay"></div>
        <h1>Fashboard</h1>
        {/* <DashboardPage /> */}
      </main>
    </>
  )
}
